// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOUyhnCdIDweKYWIazUsxZES0y3QNH-0s',
    appId: '1:881849927935:web:3839a38801ca3448a4a4ca',
    messagingSenderId: '881849927935',
    projectId: 'app-test-firebase',
    authDomain: 'app-test-firebase-fb82f.firebaseapp.com',
    storageBucket: 'app-test-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSqG8fCutY-BFcNWFByPY5CkizdXFQUZY',
    appId: '1:881849927935:android:7366bf7f8b6f9450a4a4ca',
    messagingSenderId: '881849927935',
    projectId: 'app-test-firebase',
    storageBucket: 'app-test-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfk6iEG0J6XZoEQ9GBpqkwJa6dvv44RP4',
    appId: '1:881849927935:ios:5e3d7be6401f24eba4a4ca',
    messagingSenderId: '881849927935',
    projectId: 'app-test-firebase',
    storageBucket: 'app-test-firebase.firebasestorage.app',
    iosBundleId: 'com.example.appTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfk6iEG0J6XZoEQ9GBpqkwJa6dvv44RP4',
    appId: '1:881849927935:ios:5e3d7be6401f24eba4a4ca',
    messagingSenderId: '881849927935',
    projectId: 'app-test-firebase',
    storageBucket: 'app-test-firebase.firebasestorage.app',
    iosBundleId: 'com.example.appTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOUyhnCdIDweKYWIazUsxZES0y3QNH-0s',
    appId: '1:881849927935:web:a53d6312dab207e3a4a4ca',
    messagingSenderId: '881849927935',
    projectId: 'app-test-firebase',
    authDomain: 'app-test-firebase-fb82f.firebaseapp.com',
    storageBucket: 'app-test-firebase.firebasestorage.app',
  );
}
